# Generated by Django 5.0.1 on 2026-03-17 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_autho', '0003_department_user_username_alter_user_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('IDM', 'Inter Department Meeting'), ('ODM', 'Official Department Meeting'), ('BOOTCAMP', 'Bootcamp')], max_length=10)),
                ('date_of_conduction', models.DateField()),
                ('time_of_conduction', models.TimeField()),
                ('total_participants', models.PositiveIntegerField(default=1)),
                ('agenda', models.CharField(blank=True, default='', max_length=500)),
                ('topic', models.CharField(blank=True, default='', max_length=500)),
                ('gdrive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('gdrive_pdf_id', models.CharField(blank=True, default='', max_length=255)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Required for IDM reports only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_autho.department')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
