# Generated by Django 5.2.12 on 2026-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('IDM', 'Inter Department Meeting'), ('ODM', 'Official Department Meeting'), ('BOOTCAMP', 'Bootcamp'), ('MONTHLY', 'Monthly Progress'), ('GUIDELINES', 'Guidelines & Other')], max_length=10),
        ),
    ]
