# Generated by Django 5.2.12 on 2026-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0002_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_conduction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_of_conduction',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_participants',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
