# Generated by Django 5.0.1 on 2026-04-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0003_alter_report_date_of_conduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='doc_management.report')),
            ],
        ),
    ]
